package com.example.dbadmin.repo;

import com.example.dbadmin.service.ai.AiGlossaryGap;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class AiGlossaryGapRepositoryTest {
    @Test
    void countsRepeatedMissesOfTheSameWordAsOneEntry() {
        AiGlossaryGapRepository repository = repository("ai-gap-counts");

        repository.record(7, List.of("会员", "买家"));
        repository.record(7, List.of("会员"));
        // 大小写和空格不该被当成另一个词，否则同一个说法会占三行、每行都只记一次。
        repository.record(7, List.of("  会员  "));

        assertThat(repository.findByConnectionId(7))
                .extracting(AiGlossaryGap::term, AiGlossaryGap::hits)
                .containsExactly(org.assertj.core.api.Assertions.tuple("会员", 3),
                        org.assertj.core.api.Assertions.tuple("买家", 1));
    }

    @Test
    void deletesByTheSameNormalizationItRecordedWith() {
        AiGlossaryGapRepository repository = repository("ai-gap-delete");
        repository.record(7, List.of("Buyer"));

        assertThat(repository.delete(7, List.of("  buyer "))).isEqualTo(1);
        assertThat(repository.findByConnectionId(7)).isEmpty();
    }

    @Test
    void keepsOnlyTheMostRepeatedWordsWhenTheListGrowsPastTheCap() {
        AiGlossaryGapRepository repository = repository("ai-gap-prune");
        List<String> many = new ArrayList<>();
        for (int index = 0; index < 260; index++) many.add("词" + index);

        repository.record(7, many);

        assertThat(repository.findByConnectionId(7)).hasSize(200);
    }

    @Test
    void keepsGapsOfDifferentConnectionsApart() {
        AiGlossaryGapRepository repository = repository("ai-gap-scope");

        repository.record(7, List.of("会员"));
        repository.record(8, List.of("会员"));

        assertThat(repository.findByConnectionId(7)).singleElement()
                .extracting(AiGlossaryGap::hits).isEqualTo(1);
        assertThat(repository.findByConnectionId(8)).hasSize(1);
    }

    private static AiGlossaryGapRepository repository(String name) {
        JdbcTemplate jdbc = new JdbcTemplate(new DriverManagerDataSource(
                "jdbc:h2:mem:" + name + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", ""));
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS ai_glossary_gap(
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    connection_id BIGINT NOT NULL,
                    term VARCHAR(120) NOT NULL,
                    normalized_term VARCHAR(120) NOT NULL,
                    hits INT NOT NULL DEFAULT 1,
                    first_seen_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    last_seen_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT uq_ai_glossary_gap UNIQUE (connection_id, normalized_term)
                )
                """);
        return new AiGlossaryGapRepository(jdbc);
    }
}
