package com.example.dbadmin.repo;

import com.example.dbadmin.service.ai.AiBusinessTerm;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class AiGlossaryRepositoryTest {
    @Test
    void replacesAndRestoresListFieldsAsJson() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:ai-glossary-repository;MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("""
                CREATE TABLE ai_business_glossary(
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    connection_id BIGINT NOT NULL,
                    term VARCHAR(120) NOT NULL,
                    aliases CLOB NOT NULL,
                    object_names CLOB NOT NULL,
                    description VARCHAR(1000)
                )
                """);
        AiGlossaryRepository repository = new AiGlossaryRepository(jdbc, new ObjectMapper());

        repository.replace(7, List.of(new AiBusinessTerm(0, 7, "客户",
                List.of("会员", "用户"), List.of("APP_USER", "USER_PROFILE"), "有效客户口径")));

        assertThat(repository.findByConnectionId(7)).singleElement().satisfies(entry -> {
            assertThat(entry.term()).isEqualTo("客户");
            assertThat(entry.aliases()).containsExactly("会员", "用户");
            assertThat(entry.objectNames()).containsExactly("APP_USER", "USER_PROFILE");
        });

        repository.replace(7, List.of());
        assertThat(repository.findByConnectionId(7)).isEmpty();
    }
}
