package com.example.dbadmin.service;

import db.migration.V1__BaselineSchema;
import db.migration.V10__ConnectionAccessAndAuditContext;
import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.MigrationVersion;
import org.junit.jupiter.api.Test;

import java.sql.DriverManager;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

class FlywayBaselineMigrationTest {
    @Test
    void baselinesAnExistingMetadataDatabaseAndAppliesTheIdempotentSchema() throws Exception {
        String url = "jdbc:h2:mem:flyway-existing-" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
        try (var connection = DriverManager.getConnection(url, "sa", "")) {
            connection.createStatement().execute("CREATE TABLE legacy_marker(id INT PRIMARY KEY)");
            connection.createStatement().execute("INSERT INTO legacy_marker(id) VALUES (42)");
        }

        Flyway.configure()
                .dataSource(url, "sa", "")
                .baselineOnMigrate(true)
                .baselineVersion(MigrationVersion.fromVersion("0"))
                .javaMigrations(new V1__BaselineSchema())
                .load()
                .migrate();

        try (var connection = DriverManager.getConnection(url, "sa", "")) {
            try (var tables = connection.getMetaData().getTables(null, "PUBLIC", "BACKUP_TASK", null)) {
                assertThat(tables.next()).isTrue();
            }
            try (var users = connection.getMetaData().getTables(null, "PUBLIC", "APP_USER", null)) {
                assertThat(users.next()).isTrue();
            }
            try (var marker = connection.createStatement().executeQuery("SELECT id FROM legacy_marker")) {
                assertThat(marker.next()).isTrue();
                assertThat(marker.getInt(1)).isEqualTo(42);
            }
        }
    }

    @Test
    void connectionAccessMigrationKeepsExistingConnectionsSharedAndUntouched() throws Exception {
        String url = "jdbc:h2:mem:flyway-access-" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
        try (var connection = DriverManager.getConnection(url, "sa", "")) {
            connection.createStatement().execute("CREATE TABLE app_user(id BIGINT PRIMARY KEY)");
            connection.createStatement().execute("CREATE TABLE db_connection(id BIGINT PRIMARY KEY, name VARCHAR(120), jdbc_url VARCHAR(1000))");
            connection.createStatement().execute("CREATE TABLE audit_log(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
            connection.createStatement().execute("INSERT INTO db_connection(id, name, jdbc_url) VALUES (7, 'legacy-prod', 'jdbc:legacy')");
        }

        Flyway.configure()
                .dataSource(url, "sa", "")
                .baselineOnMigrate(true)
                .baselineVersion(MigrationVersion.fromVersion("9"))
                .javaMigrations(new V10__ConnectionAccessAndAuditContext())
                .load()
                .migrate();

        try (var connection = DriverManager.getConnection(url, "sa", "")) {
            try (var row = connection.createStatement().executeQuery("""
                    SELECT c.name, c.jdbc_url, p.access_mode, p.owner_user_id
                    FROM db_connection c JOIN connection_access_policy p ON p.connection_id = c.id
                    WHERE c.id = 7
                    """)) {
                assertThat(row.next()).isTrue();
                assertThat(row.getString("name")).isEqualTo("legacy-prod");
                assertThat(row.getString("jdbc_url")).isEqualTo("jdbc:legacy");
                assertThat(row.getString("access_mode")).isEqualTo("SHARED");
                assertThat(row.getObject("owner_user_id")).isNull();
            }
            assertThat(connection.getMetaData().getColumns(null, null, "AUDIT_LOG", "REQUEST_ID").next()).isTrue();
        }
    }
}
