package com.example.dbadmin.service;

import db.migration.V1__BaselineSchema;
import db.migration.V10__ConnectionAccessAndAuditContext;
import db.migration.V13__RestoreUploadOwnership;
import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.MigrationVersion;
import org.junit.jupiter.api.Test;

import java.sql.DriverManager;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

class FlywayBaselineMigrationTest {
    @Test
    void baselinesAnExistingMetadataDatabaseAndAppliesTheIdempotentSchema() throws Exception {
        String url = "jdbc:h2:mem:flyway-existing-" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
        try (var connection = DriverManager.getConnection(url, "sa", "")) {
            connection.createStatement().execute("CREATE TABLE legacy_marker(id INT PRIMARY KEY)");
            connection.createStatement().execute("INSERT INTO legacy_marker(id) VALUES (42)");
        }

        Flyway.configure()
                .dataSource(url, "sa", "")
                .baselineOnMigrate(true)
                .baselineVersion(MigrationVersion.fromVersion("0"))
                .javaMigrations(new V1__BaselineSchema())
                .load()
                .migrate();

        try (var connection = DriverManager.getConnection(url, "sa", "")) {
            try (var tables = connection.getMetaData().getTables(null, "PUBLIC", "BACKUP_TASK", null)) {
                assertThat(tables.next()).isTrue();
            }
            try (var users = connection.getMetaData().getTables(null, "PUBLIC", "APP_USER", null)) {
                assertThat(users.next()).isTrue();
            }
            try (var marker = connection.createStatement().executeQuery("SELECT id FROM legacy_marker")) {
                assertThat(marker.next()).isTrue();
                assertThat(marker.getInt(1)).isEqualTo(42);
            }
        }
    }

    @Test
    void connectionAccessMigrationKeepsExistingConnectionsSharedAndUntouched() throws Exception {
        String url = "jdbc:h2:mem:flyway-access-" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
        try (var connection = DriverManager.getConnection(url, "sa", "")) {
            connection.createStatement().execute("CREATE TABLE app_user(id BIGINT PRIMARY KEY)");
            connection.createStatement().execute("CREATE TABLE db_connection(id BIGINT PRIMARY KEY, name VARCHAR(120), jdbc_url VARCHAR(1000))");
            connection.createStatement().execute("CREATE TABLE audit_log(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
            connection.createStatement().execute("INSERT INTO db_connection(id, name, jdbc_url) VALUES (7, 'legacy-prod', 'jdbc:legacy')");
        }

        Flyway.configure()
                .dataSource(url, "sa", "")
                .baselineOnMigrate(true)
                .baselineVersion(MigrationVersion.fromVersion("9"))
                .target(MigrationVersion.fromVersion("10"))
                .javaMigrations(new V10__ConnectionAccessAndAuditContext())
                .load()
                .migrate();

        try (var connection = DriverManager.getConnection(url, "sa", "")) {
            try (var row = connection.createStatement().executeQuery("""
                    SELECT c.name, c.jdbc_url, p.access_mode, p.owner_user_id
                    FROM db_connection c JOIN connection_access_policy p ON p.connection_id = c.id
                    WHERE c.id = 7
                    """)) {
                assertThat(row.next()).isTrue();
                assertThat(row.getString("name")).isEqualTo("legacy-prod");
                assertThat(row.getString("jdbc_url")).isEqualTo("jdbc:legacy");
                assertThat(row.getString("access_mode")).isEqualTo("SHARED");
                assertThat(row.getObject("owner_user_id")).isNull();
            }
            assertThat(connection.getMetaData().getColumns(null, null, "AUDIT_LOG", "REQUEST_ID").next()).isTrue();
        }
    }

    @Test
    void p1MigrationPreservesConnectionsAndKeepsHistoricalSnippetsShared() throws Exception {
        String url = "jdbc:h2:mem:flyway-p1-" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
        try (var connection = DriverManager.getConnection(url, "sa", "")) {
            var sql = connection.createStatement();
            sql.execute("CREATE TABLE db_connection(id BIGINT PRIMARY KEY, name VARCHAR(120), encrypted_password CLOB)");
            sql.execute("INSERT INTO db_connection VALUES (7, 'legacy-prod', 'encrypted-value')");
            sql.execute("CREATE TABLE sql_snippet(id BIGINT PRIMARY KEY, name VARCHAR(120), description VARCHAR(500), sql_text CLOB, db_type VARCHAR(40), tags VARCHAR(500), use_count BIGINT, last_used_at TIMESTAMP, actor VARCHAR(120), created_at TIMESTAMP, updated_at TIMESTAMP)");
            sql.execute("CREATE UNIQUE INDEX ux_sql_snippet_name ON sql_snippet(name)");
            sql.execute("INSERT INTO sql_snippet(id, name, sql_text, use_count, actor) VALUES (3, '旧片段', 'select 1', 0, 'admin')");
            sql.execute("CREATE TABLE sql_history(id BIGINT PRIMARY KEY, connection_id BIGINT)");
            sql.execute("CREATE TABLE app_user_group_member(group_id BIGINT, user_id BIGINT)");
            sql.execute("CREATE TABLE audit_log(id BIGINT PRIMARY KEY, actor VARCHAR(120), action VARCHAR(80), connection_id BIGINT, target VARCHAR(500), detail CLOB, remote_address VARCHAR(120), forwarded_for VARCHAR(500), user_agent VARCHAR(1000), request_id VARCHAR(120), created_at TIMESTAMP)");
            sql.execute("INSERT INTO audit_log VALUES (1, 'admin', 'CONNECTION_UPDATE', 7, 'connection:7', 'before upgrade', NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP)");
        }

        Flyway.configure().dataSource(url, "sa", "").baselineOnMigrate(true)
                .baselineVersion(MigrationVersion.fromVersion("10"))
                .target(MigrationVersion.fromVersion("11")).load().migrate();

        try (var connection = DriverManager.getConnection(url, "sa", "")) {
            var snippet = connection.createStatement().executeQuery("SELECT visibility, owner_user_id FROM sql_snippet WHERE id = 3");
            assertThat(snippet.next()).isTrue();
            assertThat(snippet.getString("visibility")).isEqualTo("SHARED");
            assertThat(snippet.getObject("owner_user_id")).isNull();
            var savedConnection = connection.createStatement().executeQuery("SELECT encrypted_password FROM db_connection WHERE id = 7");
            assertThat(savedConnection.next()).isTrue();
            assertThat(savedConnection.getString("encrypted_password")).isEqualTo("encrypted-value");
            var audit = connection.createStatement().executeQuery("SELECT event_hash FROM audit_log WHERE id = 1");
            assertThat(audit.next()).isTrue();
            assertThat(audit.getString("event_hash")).hasSize(64);
        }
    }

    /**
     * 回填要分批 executeBatch。攒满整张表再提交会把所有参数集堆在驱动内存里 —— 审计表大的
     * 实例会在升级时 OOM，而迁移这时已被标记为失败，应用直接起不来。行数取得比 BATCH_SIZE
     * 大，确保真的跨了多次刷新，并检查链在批次边界上仍然连得上。
     */
    @Test
    void p1MigrationBackfillsALargeAuditLogInBatches() throws Exception {
        int rowCount = 5_000;
        String url = "jdbc:h2:mem:flyway-p1-bulk-" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
        try (var connection = DriverManager.getConnection(url, "sa", "")) {
            var sql = connection.createStatement();
            sql.execute("CREATE TABLE db_connection(id BIGINT PRIMARY KEY, name VARCHAR(120), encrypted_password CLOB)");
            sql.execute("CREATE TABLE sql_snippet(id BIGINT PRIMARY KEY, name VARCHAR(120), description VARCHAR(500), sql_text CLOB, db_type VARCHAR(40), tags VARCHAR(500), use_count BIGINT, last_used_at TIMESTAMP, actor VARCHAR(120), created_at TIMESTAMP, updated_at TIMESTAMP)");
            sql.execute("CREATE UNIQUE INDEX ux_sql_snippet_name ON sql_snippet(name)");
            sql.execute("CREATE TABLE sql_history(id BIGINT PRIMARY KEY, connection_id BIGINT)");
            sql.execute("CREATE TABLE app_user_group_member(group_id BIGINT, user_id BIGINT)");
            sql.execute("CREATE TABLE audit_log(id BIGINT PRIMARY KEY, actor VARCHAR(120), action VARCHAR(80), connection_id BIGINT, target VARCHAR(500), detail CLOB, remote_address VARCHAR(120), forwarded_for VARCHAR(500), user_agent VARCHAR(1000), request_id VARCHAR(120), created_at TIMESTAMP)");
            try (var insert = connection.prepareStatement(
                    "INSERT INTO audit_log(id, actor, action, target, detail, created_at) VALUES (?, 'admin', 'SQL_EXECUTE', 'sql', ?, CURRENT_TIMESTAMP)")) {
                for (int i = 1; i <= rowCount; i++) {
                    insert.setLong(1, i);
                    insert.setString(2, "select " + i);
                    insert.addBatch();
                }
                insert.executeBatch();
            }
        }

        Flyway.configure().dataSource(url, "sa", "").baselineOnMigrate(true)
                .baselineVersion(MigrationVersion.fromVersion("10"))
                .target(MigrationVersion.fromVersion("11")).load().migrate();

        try (var connection = DriverManager.getConnection(url, "sa", "")) {
            var unhashed = connection.createStatement().executeQuery(
                    "SELECT COUNT(*) FROM audit_log WHERE event_hash IS NULL");
            assertThat(unhashed.next()).isTrue();
            assertThat(unhashed.getInt(1)).isZero();
            // 每一条的 previous_hash 都要等于前一条的 event_hash，批次边界上也不例外。
            var broken = connection.createStatement().executeQuery("""
                    SELECT COUNT(*) FROM audit_log current JOIN audit_log prior ON prior.id = current.id - 1
                    WHERE current.previous_hash IS DISTINCT FROM prior.event_hash
                    """);
            assertThat(broken.next()).isTrue();
            assertThat(broken.getInt(1)).isZero();
        }
    }

    @Test
    void restoreUploadOwnershipMigrationPreservesLegacyUploadsWithoutGuessingAnOwner() throws Exception {
        String url = "jdbc:h2:mem:flyway-restore-owner-" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
        try (var connection = DriverManager.getConnection(url, "sa", "")) {
            var sql = connection.createStatement();
            sql.execute("""
                    CREATE TABLE restore_upload(
                        id BIGINT PRIMARY KEY,
                        original_name VARCHAR(500),
                        expires_at TIMESTAMP
                    )
                    """);
            sql.execute("INSERT INTO restore_upload(id, original_name, expires_at) VALUES (5, 'legacy.sql', CURRENT_TIMESTAMP)");
        }

        Flyway.configure().dataSource(url, "sa", "").baselineOnMigrate(true)
                .baselineVersion(MigrationVersion.fromVersion("12"))
                .target(MigrationVersion.fromVersion("13"))
                .javaMigrations(new V13__RestoreUploadOwnership()).load().migrate();

        try (var connection = DriverManager.getConnection(url, "sa", "")) {
            var row = connection.createStatement().executeQuery(
                    "SELECT original_name, owner_user_id FROM restore_upload WHERE id = 5");
            assertThat(row.next()).isTrue();
            assertThat(row.getString("original_name")).isEqualTo("legacy.sql");
            assertThat(row.getObject("owner_user_id")).isNull();
        }
    }
}
