-- Web 多用户的连接级访问控制。策略与连接本身分表保存，升级不会改写已有连接配置。
CREATE TABLE IF NOT EXISTS app_user_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_app_user_group_name ON app_user_group(name);

CREATE TABLE IF NOT EXISTS app_user_group_member (
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (group_id, user_id),
    CONSTRAINT fk_user_group_member_group FOREIGN KEY (group_id) REFERENCES app_user_group(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_group_member_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_group_member_user ON app_user_group_member(user_id, group_id);

CREATE TABLE IF NOT EXISTS connection_access_policy (
    connection_id BIGINT PRIMARY KEY,
    access_mode VARCHAR(20) NOT NULL DEFAULT 'SHARED',
    owner_user_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_connection_access_connection FOREIGN KEY (connection_id) REFERENCES db_connection(id) ON DELETE CASCADE,
    CONSTRAINT fk_connection_access_owner FOREIGN KEY (owner_user_id) REFERENCES app_user(id) ON DELETE SET NULL
);

-- 已有连接显式标记为共享，保证升级前后的可见性和功能完全一致。
INSERT INTO connection_access_policy(connection_id, access_mode, owner_user_id)
SELECT connection.id, 'SHARED', NULL
FROM db_connection connection
WHERE NOT EXISTS (
    SELECT 1 FROM connection_access_policy policy WHERE policy.connection_id = connection.id
);

CREATE TABLE IF NOT EXISTS connection_access_grant (
    connection_id BIGINT NOT NULL,
    grantee_type VARCHAR(20) NOT NULL,
    grantee_id BIGINT NOT NULL,
    permission VARCHAR(40) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (connection_id, grantee_type, grantee_id, permission),
    CONSTRAINT fk_connection_grant_connection FOREIGN KEY (connection_id) REFERENCES db_connection(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_connection_grant_principal
    ON connection_access_grant(grantee_type, grantee_id, connection_id);

-- 审计请求上下文：remote_address 是实际 TCP 对端，forwarded_for 单独保存且不作为可信身份。
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS remote_address VARCHAR(120);
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS forwarded_for VARCHAR(500);
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS user_agent VARCHAR(1000);
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS request_id VARCHAR(120);

CREATE INDEX IF NOT EXISTS idx_audit_log_request_id ON audit_log(request_id);
