CREATE TABLE IF NOT EXISTS ai_business_glossary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    term VARCHAR(120) NOT NULL,
    aliases CLOB NOT NULL,
    object_names CLOB NOT NULL,
    description VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ai_glossary_term UNIQUE (connection_id, term),
    CONSTRAINT fk_ai_glossary_connection FOREIGN KEY (connection_id) REFERENCES db_connection(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ai_glossary_connection ON ai_business_glossary(connection_id);
