CREATE TABLE IF NOT EXISTS ai_glossary_gap (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    term VARCHAR(120) NOT NULL,
    normalized_term VARCHAR(120) NOT NULL,
    hits INT NOT NULL DEFAULT 1,
    first_seen_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ai_glossary_gap UNIQUE (connection_id, normalized_term),
    CONSTRAINT fk_ai_glossary_gap_connection FOREIGN KEY (connection_id) REFERENCES db_connection(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ai_glossary_gap_connection ON ai_glossary_gap(connection_id);
