CREATE TABLE IF NOT EXISTS mcp_settings (
    id INT PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    default_query_rows INT NOT NULL,
    max_query_rows INT NOT NULL,
    max_result_cells INT NOT NULL,
    max_result_text_chars BIGINT NOT NULL,
    max_cell_text_chars INT NOT NULL,
    max_sql_chars INT NOT NULL,
    query_timeout_seconds INT NOT NULL,
    metadata_page_size INT NOT NULL,
    max_metadata_page_size INT NOT NULL,
    table_page_size INT NOT NULL,
    max_table_page_size INT NOT NULL,
    session_ttl_minutes INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_mcp_settings_singleton CHECK (id = 1)
);

CREATE TABLE IF NOT EXISTS mcp_agent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id VARCHAR(64) NOT NULL,
    key_hash VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    allow_production BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_mcp_agent_agent_id UNIQUE (agent_id)
);

CREATE TABLE IF NOT EXISTS mcp_agent_connection (
    agent_id BIGINT NOT NULL,
    connection_id BIGINT NOT NULL,
    PRIMARY KEY (agent_id, connection_id),
    CONSTRAINT fk_mcp_agent_connection_agent FOREIGN KEY (agent_id) REFERENCES mcp_agent(id) ON DELETE CASCADE,
    CONSTRAINT fk_mcp_agent_connection_connection FOREIGN KEY (connection_id) REFERENCES db_connection(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_mcp_agent_connection_connection ON mcp_agent_connection(connection_id);

CREATE TABLE IF NOT EXISTS mcp_allowed_origin (
    origin VARCHAR(500) PRIMARY KEY
);
