-- 结构快照：某条连接的某个 Schema 在某一刻的完整表结构。
-- content 存的是按表名排序的 ObjectDetail 列表（JSON），漂移对比直接把两份反序列化后
-- 交给 SchemaComparison —— 与「结构对比」用的是同一套判定，不另写一份。
CREATE TABLE IF NOT EXISTS schema_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    schema_name VARCHAR(200) NOT NULL,
    label VARCHAR(200),
    table_count INT NOT NULL DEFAULT 0,
    checksum_sha256 VARCHAR(64) NOT NULL,
    content CLOB NOT NULL,
    captured_by VARCHAR(120),
    captured_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 再次采集得到同一个校验和时只更新这一列：时间线上留下的是「结构变了」的时刻，
    -- 而不是「我们检查过」的时刻。两者混在一起，看时间线的人分不出哪次是真的有变化。
    last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_schema_snapshot_connection FOREIGN KEY (connection_id) REFERENCES db_connection(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_schema_snapshot_scope ON schema_snapshot(connection_id, schema_name, captured_at);

-- 定期采集的目标。cron 与时区的判定和备份、定时导出同源。
CREATE TABLE IF NOT EXISTS schema_snapshot_target (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    schema_name VARCHAR(200) NOT NULL,
    cron VARCHAR(120) NOT NULL,
    schedule_zone VARCHAR(60),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    keep_snapshots INT NOT NULL DEFAULT 30,
    last_run_at TIMESTAMP,
    last_status VARCHAR(20),
    last_message VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_snapshot_target UNIQUE (connection_id, schema_name),
    CONSTRAINT fk_snapshot_target_connection FOREIGN KEY (connection_id) REFERENCES db_connection(id) ON DELETE CASCADE
);
