CREATE TABLE IF NOT EXISTS scheduled_query (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    sql_text CLOB NOT NULL,
    export_format VARCHAR(20) NOT NULL DEFAULT 'csv',
    cron VARCHAR(120) NOT NULL,
    schedule_zone VARCHAR(60),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    production_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    last_run_at TIMESTAMP,
    last_status VARCHAR(20),
    last_message VARCHAR(1000),
    last_file VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_scheduled_query_connection FOREIGN KEY (connection_id) REFERENCES db_connection(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_scheduled_query_connection ON scheduled_query(connection_id);
