CREATE TABLE IF NOT EXISTS db_connection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    db_type VARCHAR(40) NOT NULL,
    jdbc_url VARCHAR(1000) NOT NULL,
    username VARCHAR(240),
    encrypted_password CLOB,
    environment VARCHAR(40) DEFAULT 'default',
    readonly BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor VARCHAR(120) NOT NULL,
    action VARCHAR(80) NOT NULL,
    target VARCHAR(500),
    detail CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS backup_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    connection_id BIGINT NOT NULL,
    scope VARCHAR(20) NOT NULL,
    schema_name VARCHAR(240),
    table_name VARCHAR(240),
    backup_method VARCHAR(40) DEFAULT 'SQL',
    tool_path VARCHAR(1000),
    extra_args CLOB,
    native_connect_name VARCHAR(1000),
    cron VARCHAR(120),
    enabled BOOLEAN DEFAULT TRUE,
    last_status VARCHAR(40),
    last_message CLOB,
    last_file_path VARCHAR(1000),
    last_file_size BIGINT,
    last_run_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE backup_task ADD COLUMN IF NOT EXISTS last_file_path VARCHAR(1000);
ALTER TABLE backup_task ADD COLUMN IF NOT EXISTS last_file_size BIGINT;
ALTER TABLE backup_task ADD COLUMN IF NOT EXISTS backup_method VARCHAR(40) DEFAULT 'SQL';
ALTER TABLE backup_task ADD COLUMN IF NOT EXISTS tool_path VARCHAR(1000);
ALTER TABLE backup_task ADD COLUMN IF NOT EXISTS extra_args CLOB;
ALTER TABLE backup_task ADD COLUMN IF NOT EXISTS native_connect_name VARCHAR(1000);

CREATE INDEX IF NOT EXISTS idx_backup_task_connection_id ON backup_task(connection_id);

CREATE TABLE IF NOT EXISTS backup_task_table (
    task_id BIGINT NOT NULL,
    target_order INT NOT NULL,
    table_name VARCHAR(240) NOT NULL,
    PRIMARY KEY (task_id, target_order),
    CONSTRAINT uk_backup_task_table_name UNIQUE (task_id, table_name),
    CONSTRAINT fk_backup_task_table_task FOREIGN KEY (task_id) REFERENCES backup_task(id) ON DELETE CASCADE
);

INSERT INTO backup_task_table(task_id, target_order, table_name)
SELECT task.id, 0, task.table_name
FROM backup_task task
WHERE UPPER(task.scope) = 'TABLE'
  AND task.table_name IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM backup_task_table target WHERE target.task_id = task.id);

UPDATE backup_task SET scope = 'TABLES' WHERE UPPER(scope) = 'TABLE';

CREATE TABLE IF NOT EXISTS backup_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    connection_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL,
    message CLOB,
    file_path VARCHAR(1000),
    file_size BIGINT,
    started_at TIMESTAMP,
    finished_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_backup_history_task_finished ON backup_history(task_id, finished_at);

CREATE TABLE IF NOT EXISTS sql_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    sql_text CLOB NOT NULL,
    sql_type VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL,
    elapsed_ms BIGINT DEFAULT 0,
    error_message CLOB,
    actor VARCHAR(120),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sql_history_connection_id ON sql_history(connection_id, id);
