CREATE TABLE IF NOT EXISTS db_connection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    db_type VARCHAR(40) NOT NULL,
    jdbc_url VARCHAR(1000) NOT NULL,
    username VARCHAR(240),
    encrypted_password CLOB,
    environment VARCHAR(40) DEFAULT 'default',
    readonly BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor VARCHAR(120) NOT NULL,
    action VARCHAR(80) NOT NULL,
    target VARCHAR(500),
    detail CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS backup_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    connection_id BIGINT NOT NULL,
    scope VARCHAR(20) NOT NULL,
    schema_name VARCHAR(240),
    table_name VARCHAR(240),
    backup_method VARCHAR(40) DEFAULT 'SQL',
    tool_path VARCHAR(1000),
    extra_args CLOB,
    native_connect_name VARCHAR(1000),
    cron VARCHAR(120),
    enabled BOOLEAN DEFAULT TRUE,
    last_status VARCHAR(40),
    last_message CLOB,
    last_file_path VARCHAR(1000),
    last_file_size BIGINT,
    last_run_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE backup_task ADD COLUMN IF NOT EXISTS last_file_path VARCHAR(1000);
ALTER TABLE backup_task ADD COLUMN IF NOT EXISTS last_file_size BIGINT;
ALTER TABLE backup_task ADD COLUMN IF NOT EXISTS backup_method VARCHAR(40) DEFAULT 'SQL';
ALTER TABLE backup_task ADD COLUMN IF NOT EXISTS tool_path VARCHAR(1000);
ALTER TABLE backup_task ADD COLUMN IF NOT EXISTS extra_args CLOB;
ALTER TABLE backup_task ADD COLUMN IF NOT EXISTS native_connect_name VARCHAR(1000);

CREATE TABLE IF NOT EXISTS sql_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    sql_text CLOB NOT NULL,
    sql_type VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL,
    elapsed_ms BIGINT DEFAULT 0,
    error_message CLOB,
    actor VARCHAR(120),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
