-- 保存的 SQL 片段。
--
-- 执行历史只保留最近若干天并会被定期清理，反复使用的对账查询、排查脚本、清理语句
-- 没有地方安放；此前唯一的「模板」是前端硬编码的一条 SELECT 骨架。
CREATE TABLE IF NOT EXISTS sql_snippet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    sql_text CLOB NOT NULL,
    -- 为空表示适用于所有数据库类型；否则只在同类型连接上推荐。
    db_type VARCHAR(40),
    tags VARCHAR(500),
    -- 使用次数与最近使用时间用于把常用片段排到前面。
    use_count BIGINT DEFAULT 0,
    last_used_at TIMESTAMP,
    actor VARCHAR(120),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_sql_snippet_name ON sql_snippet(name);
CREATE INDEX IF NOT EXISTS idx_sql_snippet_usage ON sql_snippet(use_count DESC, id DESC);
