CREATE TABLE IF NOT EXISTS storage_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    type VARCHAR(20) NOT NULL,
    host VARCHAR(500) NOT NULL,
    port INT NOT NULL,
    base_path VARCHAR(1000),
    username VARCHAR(500),
    encrypted_password CLOB,
    smb_share VARCHAR(500),
    smb_domain VARCHAR(500),
    nfs_export_path VARCHAR(1000),
    nfs_uid INT,
    nfs_gid INT,
    nfs_groups VARCHAR(2000),
    ftp_tls_mode VARCHAR(20),
    sftp_auth_mode VARCHAR(20),
    encrypted_private_key CLOB,
    encrypted_private_key_passphrase CLOB,
    server_fingerprint VARCHAR(200),
    skip_server_verification BOOLEAN DEFAULT FALSE,
    enabled BOOLEAN DEFAULT TRUE,
    last_test_status VARCHAR(20),
    last_test_message CLOB,
    last_tested_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_storage_profile_name UNIQUE (name)
);

ALTER TABLE backup_task ADD COLUMN IF NOT EXISTS storage_profile_id BIGINT;
ALTER TABLE backup_task ADD COLUMN IF NOT EXISTS last_storage_type VARCHAR(20);
ALTER TABLE backup_task ADD COLUMN IF NOT EXISTS last_storage_profile_id BIGINT;
ALTER TABLE backup_task ADD COLUMN IF NOT EXISTS last_storage_object_key VARCHAR(2000);

ALTER TABLE backup_history ADD COLUMN IF NOT EXISTS storage_type VARCHAR(20) DEFAULT 'LOCAL';
ALTER TABLE backup_history ADD COLUMN IF NOT EXISTS storage_profile_id BIGINT;
ALTER TABLE backup_history ADD COLUMN IF NOT EXISTS storage_object_key VARCHAR(2000);
ALTER TABLE backup_history ADD COLUMN IF NOT EXISTS staging_expires_at TIMESTAMP;

UPDATE backup_history SET storage_type = 'LOCAL' WHERE storage_type IS NULL;
UPDATE backup_task SET last_storage_type = 'LOCAL'
WHERE last_storage_type IS NULL AND last_file_path IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_backup_task_storage_profile ON backup_task(storage_profile_id);
CREATE INDEX IF NOT EXISTS idx_backup_history_storage_profile ON backup_history(storage_profile_id);
CREATE INDEX IF NOT EXISTS idx_backup_history_staging_expiry ON backup_history(staging_expires_at, phase);

