-- Web 登录账号。provider + subject 是身份提供器内的稳定主键：当前仅使用 LOCAL，
-- 以后接入 OIDC/SSO 时可以复用同一账号、角色和审计链路。
CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(40) NOT NULL,
    subject VARCHAR(240) NOT NULL,
    username VARCHAR(120) NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    password_hash VARCHAR(100),
    role VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    auth_version BIGINT NOT NULL DEFAULT 0,
    last_login_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_app_user_provider_subject ON app_user(provider, subject);
CREATE UNIQUE INDEX IF NOT EXISTS ux_app_user_username ON app_user(username);
CREATE INDEX IF NOT EXISTS idx_app_user_role_enabled ON app_user(role, enabled);
